carrier_services = [
    {'carrier': 'FedEx', 'service': 'FEDEX_GROUND'},
    {'carrier': 'FedEx', 'service': 'FEDEX_2_DAY'},
    {'carrier': 'FedEx', 'service': 'FEDEX_2_DAY_AM'},
    {'carrier': 'FedEx', 'service': 'FEDEX_EXPRESS_SAVER'},
    {'carrier': 'FedEx', 'service': 'STANDARD_OVERNIGHT'},
    {'carrier': 'FedEx', 'service': 'FIRST_OVERNIGHT'},
    {'carrier': 'FedEx', 'service': 'PRIORITY_OVERNIGHT'},
    {'carrier': 'FedEx', 'service': 'INTERNATIONAL_ECONOMY'},
    {'carrier': 'FedEx', 'service': 'INTERNATIONAL_FIRST'},
    {'carrier': 'FedEx', 'service': 'INTERNATIONAL_PRIORITY'},
    {'carrier': 'FedEx', 'service': 'GROUND_HOME_DELIVERY'},
    #{'carrier': 'FedEx', 'service': 'SMART_POST'},
    {'carrier': 'FedExSmartPost', 'service': 'SMART_POST'},
    {'carrier': 'USPS', 'service': 'First'},
    {'carrier': 'USPS', 'service': 'Priority'},
    {'carrier': 'USPS', 'service': 'Express'},
    {'carrier': 'USPS', 'service': 'ParcelSelect'},
    {'carrier': 'USPS', 'service': 'LibraryMail'},
    {'carrier': 'USPS', 'service': 'MediaMail'},
    {'carrier': 'USPS', 'service': 'FirstClassMailInternational'},
    {'carrier': 'USPS', 'service': 'FirstClassPackageInternationalService'},
    {'carrier': 'USPS', 'service': 'PriorityMailInternational'},
    {'carrier': 'USPS', 'service': 'ExpressMailInternational'},
    {'carrier': 'UPSDAP', 'service': 'Ground'},
    {'carrier': 'UPSDAP', 'service': '3DaySelect'},
    {'carrier': 'UPSDAP', 'service': '2ndDayAir'},
    {'carrier': 'UPSDAP', 'service': '2ndDayAirAM'},
    {'carrier': 'UPSDAP', 'service': 'NextDayAirSaver'},
    {'carrier': 'UPSDAP', 'service': 'NextDayAir'},
    {'carrier': 'UPSDAP', 'service': 'NextDayAirEarlyAM'},
    # {'carrier': 'UPS', 'service': 'Ground'},
    # {'carrier': 'UPS', 'service': 'UPSStandard'},
    # {'carrier': 'UPS', 'service': 'UPSSaver'},
    # {'carrier': 'UPS', 'service': 'Express'},
    # {'carrier': 'UPS', 'service': 'ExpressPlus'},
    # {'carrier': 'UPS', 'service': 'Expedited'},
    # {'carrier': 'UPS', 'service': 'NextDayAir'},
    # {'carrier': 'UPS', 'service': 'NextDayAirSaver'},
    # {'carrier': 'UPS', 'service': 'NextDayAirEarlyAM'},
    # {'carrier': 'UPS', 'service': '2ndDayAir'},
    # {'carrier': 'UPS', 'service': '2ndDayAirAM'},
    # {'carrier': 'UPS', 'service': '3DaySelect'}
]