"""Initial migration.

Revision ID: 5f11385d1c33
Revises: 
Create Date: 2020-03-28 03:36:21.526938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f11385d1c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('carrier', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('discount', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_user_id'), 'discount', ['user_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('case_quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qoh_case', sa.Integer(), nullable=False),
    sa.Column('qoh_units', sa.Integer(), nullable=False),
    sa.Column('case_weight', sa.Numeric(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(), nullable=False),
    sa.Column('width', sa.Numeric(), nullable=False),
    sa.Column('height', sa.Numeric(), nullable=False),
    sa.Column('ship_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('street1', sa.String(length=50), nullable=False),
    sa.Column('street2', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postal', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=True),
    sa.Column('blind_company', sa.String(length=255), nullable=True),
    sa.Column('blind_phone', sa.String(length=25), nullable=True),
    sa.Column('customer_reference', sa.String(length=255), nullable=True),
    sa.Column('shipped', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('requested_carrier', sa.String(length=50), nullable=True),
    sa.Column('requested_service', sa.String(length=100), nullable=True),
    sa.Column('actual_carrier', sa.String(length=50), nullable=True),
    sa.Column('actual_service', sa.String(length=100), nullable=True),
    sa.Column('insurance_value', sa.Numeric(), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(), nullable=False),
    sa.Column('notify_recipient', sa.Boolean(), nullable=False),
    sa.Column('additionally_notify', sa.String(length=100), nullable=True),
    sa.Column('easypost_order_id', sa.String(length=50), nullable=True),
    sa.Column('signature_option', sa.String(length=50), nullable=True),
    sa.Column('tracking', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_table('order_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_cases', sa.Integer(), nullable=True),
    sa.Column('quantity_units', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_line_item_item_id'), 'order_line_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_order_line_item_order_id'), 'order_line_item', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_line_item_order_id'), table_name='order_line_item')
    op.drop_index(op.f('ix_order_line_item_item_id'), table_name='order_line_item')
    op.drop_table('order_line_item')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_table('order')
    op.drop_table('user_roles')
    op.drop_table('upload')
    op.drop_table('recipient')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_discount_user_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
